name: CI Pipeline

on:
  push:
    branches: [main, feature/**]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          pip install -r requirements.txt

      - name: Run Python linter (pylint)
        run: |
          pylint **/*.py

      - name: Install hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Lint Dockerfile with hadolint
        run: |
          hadolint Dockerfile

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Run unit tests
        run: |
          pytest
