name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main
      - seed
    tags:
      - 'v*'
  pull_request:

env:
  # Full image path on GHCR (replace 'handsonHivebox' with your image name)
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/handsonHivebox

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine tag and push image
        run: |
          # Normalize IMAGE_NAME to lowercase (required by GHCR)
          IMAGE_ID=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          # Extract version/tag from git ref
          VERSION=$(echo "${GITHUB_REF}" | sed -e 's,.*/\(.*\),\1,')

          # Remove 'v' prefix from tag (if it's a tag)
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${VERSION#v}
          fi

          # Use 'latest' for main branch pushes
          if [[ "$VERSION" == "main" ]]; then
            VERSION="latest"
          fi

          echo "Tagging image as $IMAGE_ID:$VERSION"

          # Tag image with version or 'latest'
          docker tag $IMAGE_NAME:latest $IMAGE_ID:$VERSION

          # Push both latest and version tags
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
